### ISSUE TITLE
Création d'un nouvel utilisateur

### ISSUE THREAD

**Issue by sbecot** [zorglub42/OSA#1]
Après la création d'un nouvel utilisateur, il n'y a pas besoin de validation. Pourtant les boutons OK et Cancel sont présents. Le bouton OK n'est pas actif, il faut donc faire Cancel pour sortir de l'écran alors qu'on ne Cancel pas puisque l'utilisateur est conservé.

**Comment by zorglub42** [comment]
Le bouton "Annuler"' devient un bouton "Retour" tant que l'utilisateur n'est pas modifié.
Lorsqu'il est modifié, le bouton est bien "Annuler"
